version: '3'
services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health_log_api_development
    ports:
      - "5433:5432" 

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/health_log_api_development

volumes:
  postgres_data:
