default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password  # PostgreSQL の実際のパスワードに統一
  host: db     # デフォルトはローカル環境向け

development:
  <<: *default
  database: health_log_api_development
  host: db  # Docker 内で接続する場合のホスト名

test:
  <<: *default
  database: health_log_api_test
