default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: '465307'
  host: health_log_api_development

development:
  <<: *default
  database: health_log_api_development
  host: db
  username: postgres
  password: postgres


test:
  <<: *default
  database: health_log_api_test
